"""empty message

Revision ID: 166c6f4fa31c
Revises: 4dcfbcbccddf
Create Date: 2024-10-02 22:22:41.408781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166c6f4fa31c'
down_revision = '4dcfbcbccddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=500),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
